AWSTemplateFormatVersion: '2010-09-09'
Description: 'Transit Gateway and Hub VPC attachment'

Parameters:
  EnvironmentName:
    Description: Environment name prefix for resources
    Type: String
    Default: Hub

  TransitGatewayDescription:
    Description: Description for the Transit Gateway
    Type: String
    Default: Central Transit Gateway for multi-account networking

Resources:
  # Transit Gateway
  TransitGateway:
    Type: AWS::EC2::TransitGateway
    Properties:
      AmazonSideAsn: 64512
      Description: !Ref TransitGatewayDescription
      AutoAcceptSharedAttachments: enable
      DefaultRouteTableAssociation: enable
      DefaultRouteTablePropagation: enable
      DnsSupport: enable
      VpnEcmpSupport: enable
      Tags:
        - Key: Name
          Value: !Sub ${EnvironmentName}-TGW

  # Transit Gateway Route Table
  TransitGatewayRouteTable:
    Type: AWS::EC2::TransitGatewayRouteTable
    Properties:
      TransitGatewayId: !Ref TransitGateway
      Tags:
        - Key: Name
          Value: !Sub ${EnvironmentName}-TGW-RouteTable

  # Hub VPC Attachment to Transit Gateway
  HubVPCAttachment:
    Type: AWS::EC2::TransitGatewayAttachment
    Properties:
      TransitGatewayId: !Ref TransitGateway
      VpcId: !ImportValue 
        Fn::Sub: ${EnvironmentName}-VPC-ID
      SubnetIds:
        - !ImportValue 
            Fn::Sub: ${EnvironmentName}-PrivateSubnet1-ID
        - !ImportValue 
            Fn::Sub: ${EnvironmentName}-PrivateSubnet2-ID
      Tags:
        - Key: Name
          Value: !Sub ${EnvironmentName}-VPC-TGW-Attachment

  # Associate Hub VPC with TGW Route Table
  HubVPCRouteTableAssociation:
    Type: AWS::EC2::TransitGatewayRouteTableAssociation
    Properties:
      TransitGatewayAttachmentId: !Ref HubVPCAttachment
      TransitGatewayRouteTableId: !Ref TransitGatewayRouteTable

  # Enable route propagation for Hub VPC
  HubVPCRouteTablePropagation:
    Type: AWS::EC2::TransitGatewayRouteTablePropagation
    Properties:
      TransitGatewayAttachmentId: !Ref HubVPCAttachment
      TransitGatewayRouteTableId: !Ref TransitGatewayRouteTable

  # Add routes to Hub VPC private route tables pointing to TGW
  # Route for Spoke A VPC (10.1.0.0/16)
  HubPrivateRoute1ToSpokeA:
    Type: AWS::EC2::Route
    DependsOn: HubVPCAttachment
    Properties:
      RouteTableId: !ImportValue 
        Fn::Sub: ${EnvironmentName}-PrivateRouteTable1-ID
      DestinationCidrBlock: 10.1.0.0/16
      TransitGatewayId: !Ref TransitGateway

  HubPrivateRoute2ToSpokeA:
    Type: AWS::EC2::Route
    DependsOn: HubVPCAttachment
    Properties:
      RouteTableId: !ImportValue 
        Fn::Sub: ${EnvironmentName}-PrivateRouteTable2-ID
      DestinationCidrBlock: 10.1.0.0/16
      TransitGatewayId: !Ref TransitGateway

  # Route for Spoke B VPC (10.2.0.0/16)
  HubPrivateRoute1ToSpokeB:
    Type: AWS::EC2::Route
    DependsOn: HubVPCAttachment
    Properties:
      RouteTableId: !ImportValue 
        Fn::Sub: ${EnvironmentName}-PrivateRouteTable1-ID
      DestinationCidrBlock: 10.2.0.0/16
      TransitGatewayId: !Ref TransitGateway

  HubPrivateRoute2ToSpokeB:
    Type: AWS::EC2::Route
    DependsOn: HubVPCAttachment
    Properties:
      RouteTableId: !ImportValue 
        Fn::Sub: ${EnvironmentName}-PrivateRouteTable2-ID
      DestinationCidrBlock: 10.2.0.0/16
      TransitGatewayId: !Ref TransitGateway

Outputs:
  TransitGatewayId:
    Description: Transit Gateway ID
    Value: !Ref TransitGateway
    Export:
      Name: !Sub ${EnvironmentName}-TGW-ID

  TransitGatewayRouteTableId:
    Description: Transit Gateway Route Table ID
    Value: !Ref TransitGatewayRouteTable
    Export:
      Name: !Sub ${EnvironmentName}-TGW-RouteTable-ID

  HubVPCAttachmentId:
    Description: Hub VPC Transit Gateway Attachment ID
    Value: !Ref HubVPCAttachment
    Export:
      Name: !Sub ${EnvironmentName}-VPC-TGW-Attachment-ID
